kind = "api"
previewPath = "/"
title = "GanitProperties"
version = "1.0.0"

[[services]]
localPort = 5000
name = "GanitProperties"
paths = ["/"]

[services.development]
run = "cd patiala-property-finder && python app.py"

[services.production]

[services.production.build]
args = ["pip", "install", "-r", "patiala-property-finder/requirements.txt"]

[services.production.run]
args = ["sh", "-c", "cd patiala-property-finder && python app.py"]

[services.production.run.env]
NODE_ENV = "production"

[services.production.health.startup]
path = "/"
