from .base import BaseScraper


class DemoScraper(BaseScraper):
    """
    Demo scraper — loads sample Patiala listings so the app has data
    from the very first run. Replace or extend with real scrapers.
    """

    def fetch(self) -> list[dict]:
        return [
            {
                "title": "3 BHK House in Model Town, Patiala",
                "price": "₹75 Lakh",
                "location": "Model Town",
                "area": "1800 sq ft",
                "property_type": "House",
                "listing_type": "Buy",
                "summary": "Spacious 3 BHK independent house with covered parking and garden in a prime colony.",
                "source_url": "https://example.com/patiala-model-town-3bhk-001",
                "source_name": "Demo Data",
            },
            {
                "title": "2 BHK Flat for Rent near Punjabi University",
                "price": "₹9,000/month",
                "location": "Punjabi University Road",
                "area": "950 sq ft",
                "property_type": "Flat",
                "listing_type": "Rent",
                "summary": "Well-maintained 2 BHK flat ideal for students and small families, close to Punjabi University.",
                "source_url": "https://example.com/patiala-punjabi-university-2bhk-rent-001",
                "source_name": "Demo Data",
            },
            {
                "title": "Plot for Sale in Sector 22, Patiala",
                "price": "₹28 Lakh",
                "location": "Sector 22",
                "area": "200 sq yd",
                "property_type": "Plot",
                "listing_type": "Buy",
                "summary": "Residential plot with clear title in a developing sector with good connectivity.",
                "source_url": "https://example.com/patiala-sector22-plot-001",
                "source_name": "Demo Data",
            },
            {
                "title": "4 BHK Villa in Urban Estate, Patiala",
                "price": "₹1.2 Crore",
                "location": "Urban Estate",
                "area": "3200 sq ft",
                "property_type": "Villa",
                "listing_type": "Buy",
                "summary": "Luxury 4 BHK villa with modular kitchen, 3 bathrooms, and a lush garden in Urban Estate Phase II.",
                "source_url": "https://example.com/patiala-urban-estate-villa-001",
                "source_name": "Demo Data",
            },
            {
                "title": "1 BHK Flat on Rent in Tripuri Town",
                "price": "₹6,500/month",
                "location": "Tripuri Town",
                "area": "550 sq ft",
                "property_type": "Flat",
                "listing_type": "Rent",
                "summary": "Affordable 1 BHK flat with attached bathroom, suitable for bachelors or working professionals.",
                "source_url": "https://example.com/patiala-tripuri-1bhk-rent-001",
                "source_name": "Demo Data",
            },
            {
                "title": "Commercial Shop in Old Leh Road Market",
                "price": "₹55 Lakh",
                "location": "Old Leh Road",
                "area": "320 sq ft",
                "property_type": "Commercial",
                "listing_type": "Buy",
                "summary": "Ground-floor commercial shop in a busy market area, ideal for retail or service business.",
                "source_url": "https://example.com/patiala-old-leh-road-shop-001",
                "source_name": "Demo Data",
            },
            {
                "title": "2 BHK Builder Flat in Ropar Road",
                "price": "₹38 Lakh",
                "location": "Ropar Road",
                "area": "1050 sq ft",
                "property_type": "Flat",
                "listing_type": "Buy",
                "summary": "New 2 BHK builder flat with lift, power backup, and covered parking. Ready to move in.",
                "source_url": "https://example.com/patiala-ropar-road-flat-001",
                "source_name": "Demo Data",
            },
            {
                "title": "3 BHK Independent House for Rent in Leela Bhawan",
                "price": "₹18,000/month",
                "location": "Leela Bhawan",
                "area": "1600 sq ft",
                "property_type": "House",
                "listing_type": "Rent",
                "summary": "Well-kept 3 BHK house on main road with 2 balconies, open car parking, and 24hr water supply.",
                "source_url": "https://example.com/patiala-leela-bhawan-house-rent-001",
                "source_name": "Demo Data",
            },
            {
                "title": "Agricultural Land near Rajpura Bypass",
                "price": "₹22 Lakh per acre",
                "location": "Rajpura Bypass",
                "area": "5 acres",
                "property_type": "Plot",
                "listing_type": "Buy",
                "summary": "Fertile agricultural land with tube-well access, suitable for farming or investment near the bypass.",
                "source_url": "https://example.com/patiala-rajpura-land-001",
                "source_name": "Demo Data",
            },
            {
                "title": "Studio Apartment for Rent near NIT Campus",
                "price": "₹5,000/month",
                "location": "NIT Campus Road",
                "area": "400 sq ft",
                "property_type": "Flat",
                "listing_type": "Rent",
                "summary": "Compact studio apartment perfect for NIT students, fully furnished with attached washroom.",
                "source_url": "https://example.com/patiala-nit-studio-001",
                "source_name": "Demo Data",
            },
            {
                "title": "5 Marla Plot in New Lal Bagh Colony",
                "price": "₹18 Lakh",
                "location": "Lal Bagh Colony",
                "area": "5 Marla",
                "property_type": "Plot",
                "listing_type": "Buy",
                "summary": "Residential plot in a calm residential colony with clean title. Ready for immediate construction.",
                "source_url": "https://example.com/patiala-lal-bagh-plot-001",
                "source_name": "Demo Data",
            },
            {
                "title": "2 BHK Flat for Sale in Sector 4",
                "price": "₹32 Lakh",
                "location": "Sector 4",
                "area": "900 sq ft",
                "property_type": "Flat",
                "listing_type": "Buy",
                "summary": "Ready-to-move 2 BHK flat on 3rd floor with good ventilation and east-facing balcony.",
                "source_url": "https://example.com/patiala-sector4-2bhk-001",
                "source_name": "Demo Data",
            },
        ]
